### ISSUE TITLE
Error: write after end with basic usage

### ISSUE THREAD

**Issue by famousketchup** [Craga89/gulp-watch-less#6]
When doing things mostly like in `README`, I get this:

```
[12:27:40] LESS saw main.less was changed
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at write (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/gulp-watch/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/gulp-watch/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at Duplex.pipeOnReadable (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/gulp-watch/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at Duplex.emit (events.js:104:17)
    at emitReadable_ (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/gulp-watch/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/gulp-watch/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/gulp-watch/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at Duplex.Readable.push (/media/shared/srv/http/work/island/docupace/docupace-ui/node_modules/gulp-watch-less/node_modules/gulp-watch/node_modules/readable-stream/lib/_stream_readable.js:149:10)
```

`Gulp` version is:

```
CLI version 3.9.0
Local version 3.9.0
```

Hope it's easily resolvable. Thanks

**Comment by MadLittleMods** [comment]
:+1: `gulp@3.8.1`, `gulp-watch-less@1.0.1`

**Comment by vhmth** [comment]
Same issue for me. `gulp@3.9.1` and `gulp-watch-less@1.0.1`.
